### ISSUE TITLE
locking

### ISSUE THREAD

**Issue by ElizabethMartinez2021** [Montellese/cpp-cache#1]
I tried out your cpp-cache library and it is really nice!  I could not figure out how to set the:

- threading policy
- storage policy

Would you be so kind as to provide a demo simply **initializing ttl_cache** with **locking** and if possible, a **storage policy** too?

Thank you!

**Comment by Montellese** [comment]
Please see [threading policy](https://github.com/Montellese/cpp-cache#threading-policy) in the `README.md` on threading / locking policy. `cpp-cache` support very basic locking. By default it uses the `cpp_cache::no_locking` policy which does nothing. But you can just explicitly pass `std::mutex` and it will use that for locking. But beware in C++11 there is / was very limited threading / locking support in the STL. Therefore the lock is used around every operation including reading. Obviously a shared mutex / lock would be better because reading can happen simultenously without any issues while writing requires a unique lock. With C++14 / 17 these things become possible and I'll look into it when I get time.

As for an example with threading and storage policy
```cpp
#include <cpp-cache/ttl-cache.h>
#include <cpp-cache/storage/map.h>

#include <mutex>
#include <string>

cpp_cache::ttl_cache<int, std::string, 100000, cpp_cache::storage::map<Key, T>, std::mutex> ttl_cache;
```

**Comment by ElizabethMartinez2021** [comment]
Thank you very much Sascha, I have now added std::mutex like you said.  I've never used std::shared_mutex before but I can see the huge benefit of exclusive reads and shared writes.  From cppreference website:

```
  // Multiple threads/readers can read the counter's value at the same time.
  unsigned int get() const {
    std::shared_lock lock(mutex_);
    return value_;
  }
 
  // Only one thread/writer can increment/write the counter's value.
  void increment() {
    std::unique_lock lock(mutex_);
    value_++;
  }

```
For my use case, std::mutex is is perfectly acceptable, but I do see how a shared lock would help any caching system.

Thank you once again and may God bless.
